### ISSUE TITLE
No longer builds on 0.10

### ISSUE THREAD

**Issue by dbkaplun** [atom/text-buffer#117]
```
/home/travis/.node-gyp/0.10.41/deps/v8/include/v8.h:146:37: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
     *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
```

See log: https://travis-ci.org/slap-editor/editor-widget/jobs/95408774
